import { test, expect } from '@playwright/test';
test('test', async ({ page }) => {
  await page.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dswag%2Blabs%26oq%3Dswag%2Blabs%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDI4MjdqMGoyqAIAsAIB%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3Dz22sZ7TjJOTm7_UPuZewmQ0&q=EgRzups8GNDbsb0GIjDz2FUemB2d6GCDM8IJCkqsrUpLvwPzUFd7EMdd14MZpqDfQhvfddfBfSHTn05vk8UyAXJaAUM');
  await page.locator('iframe[name="a-dfapemsal8gg"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('.rc-imageselect-tile').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(2)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(3)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(3)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(3)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(2)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('div').filter({ hasText: /^Verify$/ }).nth(2).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('.rc-imageselect-tile').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(2)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('.rc-imageselect-tile').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(2)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(2)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('.rc-imageselect-tile').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().locator('td:nth-child(2)').first().click();
  await page.locator('iframe[name="c-dfapemsal8gg"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('link', { name: 'Swag Labs Swag Labs https://' }).click();
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('problem_user');
  await page.locator('[data-test="username"]').press('Tab');
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await page.getByRole('link', { name: 'Logout' }).click();
  await page.pause()
});